---
# reference: https://github.com/kubernetes-operators-book/chapters/blob/master/ch05/database.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: dpcreator-db-data-configmap
data:
  #
  # Database settings for postgres and Django
  #
  DB_HOST: "postgres-service"
  DB_PORT: "5432"
  DB_ENGINE: "django.db.backends.postgresql_psycopg2"
  #
  # These two variables should have the same value (kludge):
  POSTGRES_DB: "db_dpcreator"
  DB_NAME: "db_dpcreator"
---
# ---------------------------
# DPCreator - Postgres Deployment
# ---------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dpcreator
      tier: postgres
  template:
    metadata:
      labels:
        app: dpcreator
        tier: postgres
    spec:
      volumes:
        # Persistent Disk space to store Postgres files
        #  Used by dpcreator-postgres container
        #- name: postgres-persistent-volume
        #  azureDisk:
        #    kind: Managed
        #    diskName: dpcreator-postgres-02
        #    diskURI: /subscriptions/14d2f886-16d9-4a5b-87f0-7aa1c4608026/resourceGroups/MC_DPCreatorResourceGroup_DPCreatorCluster01_eastus/providers/Microsoft.Compute/disks/dpcreator-postgres-02
      containers:
        - name: dpcreator-postgres
          image: postgres:13
          imagePullPolicy: Always
          ports:
            - name: postgres-port
              containerPort: 5432
              protocol: TCP
          # Persistent Disk space to store Postgres files
          #volumeMounts:
          #- name: postgres-persistent-volume
          #  mountPath: /var/lib/postgresql/data
          envFrom:
          - configMapRef:
              name: dpcreator-db-data-configmap
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-auth-secret
                  key: db_username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-auth-secret
                  key: db_password
---
# ---------------------------
# DPCreator - Postgres Service
# ---------------------------
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  labels:
    app: dpcreator
    tier: postgres
spec:
  clusterIP: None
  ports:
    - port: 5432
  selector:
    app: dpcreator
    tier: postgres